language: node_js
node_js:
  - 'node'
  - '6'
  - '5'
  - '4'
script: npm run travisci
after_script:
  - codeclimate-test-reporter < coverage/lcov.info
addons:
  code_climate:
    repo_token:
      secure: "nOg04E5v4RFgo1Lw1nq9qWIJyR8SSZXwoR5iZoKM9jZVt03HkYm8U7ETbYtQKpBXpV7Q8+dPJ2BW3m2nTW8tPhKdbJyVAQgqjW15OhUNz0uq2V0rJV4Uea5OFDWAEhi2EYAPgAE842pofbys4HDsr3cvr1Mcs+/yI0OdQu9qmf7sfDsDlg4gS1vCme3G7RwoUXuSySmg9qqVVCj42YqaiiBgMGqq3Ke4ewIEiDXYTYXwCHbjfD03s5mbO6wMA7gD20wtvZx0pgriZ/gAwu3nRkl9a605D/AUMzvXOhk3W1ZYUlPFE5VwCVI4Srwq93m+b5B23/8XHRG9tkRAk0U46Q9GVl9L0HFpwS+w00SngPplMg3zyOKzWtdswO6vpwkAf48LUSOfYpjU2O9D+KuT1XSnujXPx+/HLOit+MRJkDzzggKrXnjF5+ctT29oTLnBqQV6D2cFzhzlaW5NKmbRrBSlvrlLeFMKKNFG2GVmX/2M9mjTk4GDLyc8b1SuaO1Kcr3F3Klb/dv+SR7jDyGi8dzNCDukaTnZlzbIeqh2+jZhmcEO+47ihvICKpSARJM9YG+d+xv7o4ftOTlyTbZrAq+oiC5YzKfOXYTOZrX7kKklRFBGqn/+jZwxzWAwLm1UEscdId4GQhrhNNFDh7NiRMkVR4IPxT7YDRZ9G00FV78="
